---
##
# Add a new user.
#
# user_name: The name of the new user, will also be used for group name.
#
- hosts: all
  sudo: yes

  vars_prompt:
    user_name: "User name?"

  tasks:

    - name: Create user group.
      action: group name={{ user_name }}

    - name: Create the user account.
      action: user name={{ user_name }} group={{ user_name }} shell=/bin/bash state=present

    - name: SSH Folder.
      action: file path=/home/{{ user_name }}/.ssh state=directory owner={{ user_name }} group={{ user_name }} mode=755

    - name: WWW Folder.
      action: file path=/home/{{ user_name }}/www state=directory owner={{ user_name }} group={{ user_name }} mode=755
