---
##
# Ansible setup.
#
- name: Ansible | Add Ansible PPA
  apt_repository: repo='ppa:ansible/ansible' validate_certs=no

- name: Ansible | Update apt cache
  action: apt update_cache=yes

- name: Ansible | Install required packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - software-properties-common
    - ansible
