---
##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed

- name: Node.js | Add the node.js PPA
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes

- name: Node.js | Install nodejs and npm
  action: apt pkg=nodejs state=installed

- name: Node.js | Install required npm packages
  action: command npm install -g bower coffee-script grunt-cli jshint
